### PR TITLE
Port to Python3.

### PR DESCRIPTION
**Pull request by marxin**
I used 2to3 script and then I clean up result of the conversion.

### CODE REVIEW

**Comment by martialblog** [comment]
Awesome!

**Comment by marxin** [comment]
Broader testing of the conversion would be appreciated.

**Comment by martialblog** [comment]
Gonna merge this into a python3 Branch, which will be used for testing and futher development. 

Thanks for the PR!

**Comment by marxin** [comment]
Thank you. I'm suggesting to do a Python3-based release as soon as possible. Python2 is obsolete for more than 10 years :D

**Pull request merged**
