### PR TITLE
pull improvements from different branches together

### PR DESCRIPTION
**Pull request by bb-Ricardo**
* adding support for (*)  (49502253934fc7b293d24a095dac7c4266f94a0d)
* added '-k', '--insecure' option to ignore cert errors (e4633696717705360f1c3ee48f7a4cb3f2eacdf4)
* added '-y' and 'Y' not equal option  (d164a1250cdb13491d5084b2d31d7d32e2808567)
* add client ssl cert support (67136a4a2bf4ad3479e35034ca10e9dff7ccc1b8)
* improved output of values (9dd6323b85b9541bc353a7cecf4e1ada97225e26, 965626543965ca3dada49d26204ca6777af656ec)
* return more meaningful error message if parsing of data or ssl certs/keys failed (d98d0396b2885f23756cb6ea3ba2f2581401a194, 8437c464e539665984ca816ef694f29bed916750)
* added Unknown option (27eaaf084263bb7d38de1621449e4e22a1b49dd8)
* added version information and improved help text (bcc36a6e95b6e16d5d4c659a6097e870aeace98e)
* Added default User-Agent header (7858382bbed7b83f77457faa36b4f5e3f0331b54)

Fixes: #45 
Fixes: #28 
Fixes: #24

### CODE REVIEW

**Comment by marxin** [comment]
Hello. Is there any progress about this.
I made #45 which is listed in this PR, but still waiting to be merged..

**Comment by martialblog** [comment]
Hi, I'll have a look at these changes and then merge it.

**Comment by marxin** [comment]
> Hi, I'll have a look at these changes and then merge it.

Thanks. Are you planning to do a release soon?

**Comment by martialblog** [comment]
@marxin Just did! After 1.4, I probably try to move this plugin to Python 3 which will then be v2.*

**Pull request merged**
